version: "3"

services:
  weatherapi:
    image: "weatherapi:1.0"
  nginx:
    image: "nginx:1.21.1-alpine"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weatherapi
    ports:
      - "8888:8888"